apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: catfish-cluster
  region: us-east-1

managedNodeGroups:
  - name: catfish-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 20
    ssh: 
      allow: true # Useful for debugging nodes later
