apiVersion: apps/v1
kind: Deployment
metadata:
  name: catfish-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catfish-shop
  template:
    metadata:
      labels:
        app: catfish-shop
    spec:
      containers:
      - name: catfish-container
        image: docker.io/library/catfish-app-v2:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
