apiVersion: v1
kind: Service
metadata:
  name: catfish-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: catfish-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
